### ISSUE TITLE
[Consolidated Channel] kafka-ch-controller keeps open connections to Kafka when KafkaChannel is deleted

### ISSUE THREAD

**Issue by maschmid** [knative-sandbox/eventing-kafka#564]
**Describe the bug**
On a cluster where KafkaChannels are frequently created and deleted, the number of open TCP connections to Kafka from kafka-ch-controller keeps increasing.

 **Expected behavior**
TCP connections to Kafka should be eventually closed after KafkaChannels are deleted.

 **To Reproduce**
Create and delete KafkaChannels, e.g. like
https://gist.github.com/maschmid/d4f1d0d545dee912a6c84dd8869d65b6

notice the TCP connections are kept open long after no kafkachannels are present on the cluster, e.g. by listing /proc/net/tcp inside the kafka-ch-controller

 **Knative release version**
0.20

 **Additional context**
Reproduced on OpenShift 4.7, knative installed via OpenShift Serverless 1.14

**Comment by slinkydeveloper** [comment]
I've checked for any leak of the kafka admin client:

* In `ReconcileKind` @devguyio added a patch recently to close the admin client https://github.com/knative-sandbox/eventing-kafka/commit/c4ff783520580953d0ae397708c764815932b6ba#diff-8d0207acc30e8507b21472d7c7ec7070441d085b47345fc60e6f53ec601da3fdR165, so that should be ok
* The same thing was missing in `FinalizeKind`, here is a PR for it: https://github.com/knative-sandbox/eventing-kafka/pull/565
