### ISSUE TITLE
[consolidated ch] Unnecessary restart of dispatcher pod(s)

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka#570]
**Describe the bug**

from @matzew 

the configmap-hash is empty ( "") on first startup: https://github.com/knative-sandbox/eventing-kafka/commit/0decad4cd74fcd1d5e15b2b160ef9fa2173304de#diff-2932656ebe01ef3d25[…]07f4e4232aae131cdb95fR35

Now, when I create a channel we hit: https://github.com/knative-sandbox/eventing-kafka/blob/main/pkg/channel/consolidated/reconciler/controller/kafkachannel.go#L383-L387    and the dispatcher deployment is updated.

Perhaps OK... since by default... we have replicas: 0  BUT.... when I change that (e.g. in here: https://github.com/knative-sandbox/eventing-kafka/blob/main/config/channel/consolidated/deployments/dispatcher.yaml#L25 )   all of my pods are terminated/recreated b/c of that :slightly_smiling_face:

Not sure if we could do a bit more of optimization here

 **Expected behavior**
No unnecessary restart of the dispatcher pod

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by devguyio** [comment]
@matzew 
1. why would you install with the dispatcher replicas set to 1 already? is it to start with the replicaset scaled to more than 1 pod?
2. I believe it's gonna be hard for the controller to deduce which configmap is the dispatcher aware of unless it redeploys it. Say you're installing for the first time `ko apply -f config/...`  where you set the replicas to 1 upfront, that ends up with the controller pod and dispatcher pod , how will the controller know which configmap does the current dispatcher see right now? the contract is that the annotation reflects the configmap the dispatcher sees right now. I believe this is by design, controller `enforces` the dispatcher redeployment by injecting the annotation. 

The two options for a good UX I see are:
1. If the user has no intention to control of the dispatcher deployment. They just want To start with a dispatcher replicaset scaled to 0. And let the flow go from there. (they create a channel, a dispatcher scales to 1 with correct annotation, etc)
2. If the user needs to start with the "correct" setup and a  dispatcher already scaled , then they need to make sure the annotation is populated correctly with the correct hash. That's the only way to inform the controller which version of the configmap is the dispatcher seeing.

I think after thinking about this, I believe it's a mistake that the user directly scales up and down the dispatcher. I believe the direction now is that the controller is responsible of the dispatcher lifecyle. So why not have a config map for the controller with a setting for the dispatcher replicas, and then all the user needs to do is to change the configmap, and let the controller scale it up or down?
