### ISSUE TITLE
Allow user defined annotations for kafka channel dispatchers and receivers

### ISSUE THREAD

**Issue by derekwilliamsliquidx** [knative-sandbox/eventing-kafka#613]
**Problem**
I have a need to annotate dispatcher and receiver pods so that I can scrape logs and metrics with Datadog. While I could accomplish this with Fluentbit or Jaeger, all other resources within my cluster allow custom annotations. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
This feature is targeted at a Cluster Admin and/or developer.

**Exit Criteria**
As a cluster admin, I am able to add custom annotations to my dispatcher/receiver pods, validate that the pods have the annotations I expect and the annotations provide the behavior I expect.

**Comment by ssandanshi** [comment]
I would also like if more specs for the dispatcher and receiver deployments are exposed. The easiest way is definitely through the config map. we already have control over the replicas, resources and other things mentioned by derek. 

Our feature requests also include ability to provide affinity/node selectors, (preferably scoped per channel through channel spec for dispatcher, but global config setting is a great start). I can create a separate issue for that if needed

**Comment by aliok** [comment]
+1 on ideas here. We already have some specs available to setup within the configmap (e.g. CPU resources). We can have these there too.

**Comment by PatrickOsborne** [comment]
I have a need to add istio custom annotations for CPU and memory requests for istio sidecar container.  This is imperative to scale up our solution for production use.

These need to be added to the deployment spec of the receiver and dispatcher pods.

     annotations:
        sidecar.istio.io/proxyCPU: 1000m
        sidecar.istio.io/proxyMemory: 200Mi

**Comment by aliok** [comment]
For consolidated channel implementation, you may manually modify the Deployment here: https://github.com/knative-sandbox/eventing-kafka/blob/main/config/channel/consolidated/deployments/dispatcher.yaml#L16

It starts with `replicas: 0` and when there's a Kafka Channel created, the controller will scale it to 1 replica, leaving the other parts of the Deployment spec untouched.

@eric-sap Does this also work with distributed channel implementation?

**Comment by eric-sap** [comment]
I believe that in the distributed implementation, you can similarly add a label to the deployments that will not be erased when the configmap changes.  This may be sufficient for the receiver (which is one-per-cluster, though is not created until the first KafkaChannel is reconciled in the latest incarnation), but the distributed dispatcher is a more interesting beast.  Since it is one-per-KafkaChannel it may not be practical to direct users of that channel type to manually modify the deployments every time a new KafkaChannel is added.

**Comment by eric-sap** [comment]
The other issue is that deployments in the distributed channel are generated internally (see newDispatcherDeployment() in pkg/channel/distributed/controller/kafkachannel/dispatcher.go) so modifying the deployment isn't as simple as modifying a static YAML file.  I don't actually know the reason for this; there may be something necessarily-dynamic in there but I would need to examine that code a bit more to answer that for certain.

**Comment by eric-sap** [comment]
For the dispatcher, the reasons for having the deployment internally-generated are:
* The name needs to be unique-per-kafkachannel (using util.DispatcherDnsSafeName)
* A number of environment variables are configurable (typically from the controller's own variables)
* The resource requests and limits are configurable (via config-kafka)
* Some other miscellaneous settings (liveness/readiness values, etc) which are code-constants

Most of those settings could be defaulted (or missing) in a constant dispatcher.yaml file and modified during reconciliation as I believe the consolidated channel does with the glaring exception of the actual name of the deployment.  That needs to be unique and it can't be renamed later (not in a simple manner at any rate).

The receiver deployment is very similar, although we do have plans to make the receiver name a constant rather than being based on the name of the authentication secret (defaults to "kafka-cluster"), it is currently a dynamically-named resource just like the dispatcher.

Modifications to the way those deployments are generated is certainly possible but is not a trivial matter.  A mechanism for adding custom annotations and labels (and other things) would (in my opinion) likely be the better option.  Everything need not be added at once as long as they are just separate sections in the configmap; the JSON mapper that handles the EventingKafkaConfig struct (loadEventingKafkaSettings() in pkg/common/kafka/sarama/sarama.go for the struct defined in pkg/common/config/eventingkafkaconfig.go) makes it fairly easy to add optional sections.

**Comment by travis-minke-sap** [comment]
Yeah, I agree with what Eric has posted above.  The fact that the distributed channel dynamically creates the Receiver / Dispatcher implies the need to provide the "custom" configuration (labels, annotations, etc).

I think exposing the ability for the user to specify a set of custom **labels** and **annotations** for receivers/dispatchers would solve 80-90% of the problem and is probably good enough?  We could look into more complicated templating patterns I suppose - I think @lionelvillard had created a preliminary proposal / Issue related to that some time back (can't find the issue) but I thought it was a higher level Knative idea and would probably take a lot of time and effort to work into the specs, etc...

**Comment by lionelvillard** [comment]
FWIW, here:
- the design doc draft: https://docs.google.com/document/d/1VvlgoWP1_enKIaH9LBbGkLvwWUluLjPdtPezULCmzfE/edit?resourcekey=0-MFetW356DuH58TntTv3CjQ#
- and PingSource PR: https://github.com/knative/eventing/pull/4731

The initial effort is targeting vendors, not the users, since *in general*, I'm opposed to allow users to specify labels and annotations due to the implementation leaking through. However, IMO, it makes total sense for the distributed/consolidates/stkafkasource implementations to propagate them.

**Comment by aliok** [comment]
@lionelvillard Can we move it one step forward? How about an approach similar to the Knative operator? AFAIK, you can give the Knative operator a URL to download the manifests (YAML). If no URL is given, it simply uses the manifests that's in the image.

**Comment by lionelvillard** [comment]
@aliok not sure I fully understand your proposal. What would be the UX without using the Knative operator? Does your proposal give the ability for the user to specify a set of custom labels and annotations?
