### ISSUE TITLE
Reevaluate confluent-kafka-go decision 

### ISSUE THREAD

**Issue by davyodom** [knative-sandbox/eventing-kafka#8]
confluent-kafka-go was originally chosen for this channel implementation over sarama for several reasons (this was more than a year ago)
- Ordering was not guaranteed in error cases by sarama producer
- consumer group distribution with sarama-cluster over multiple processes elastically had issues
- manual offset commit support lacking in sarama
- only supported older kafka versions and did not have full kafka feature support
- confluent backing of confluent-kafka-go and librdkafka is more or less guaranteed and kept up to date

The choice of confluent-kafka-go does introduce some challenges though, primarily around cgo builds.  This causes a divergence in developer experience here vs all other knative components.  We should revisit the initial reasons for the choice as a lot has changed since then, and see if the decision is still justified.  Performance, and open source community / governance model should also be taken into consideration and discussion.

**Comment by slinkydeveloper** [comment]
Completely off topic _but not so much_, @pierDipi proposed to create the alternative kafka broker using java for the data-plane, exactly to avoid issues with "half baked" kafka golang libs:  https://docs.google.com/document/d/10-qylWrj7Tj81EqoIiZ2AANAZNmkKe7XKmFobgZULKY/edit?usp=sharing

**Comment by davyodom** [comment]
/assign @phamilton
prow was broken before :)

**Comment by phamilton** [comment]
Please find our performance comparison results here https://github.com/phamilton/go-kafka-benchmark. From a performance POV it is clear that except when utilizing the Azure EventHubs Kafka compatibility layer Sarama performance is significantly better than that provided by confluent-kafka-go and is comparable to the Java client in most cases.

Since using the Kafka layer of Azure EventHubs is likely pretty rare, and also based on the performance we see, not a great choice. It doesn't seem like that should be a blocker to switch to Sarama.

From a functional standpoint we did not find any blockers for moving to Sarama.

**Comment by lionelvillard** [comment]
> comparable to the Java client in most cases

it seems the Java client is much faster on the producer side. Any insights on why?

**Comment by pierDipi** [comment]
From a quick look, it seems like default configurations among libraries are different.

For example, `acks`
- `Java` = `1` - see https://kafka.apache.org/documentation/#producerconfigs
- `librdkafka` = `-1` = `all brokers` - see https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md#topic-configuration-properties
- `sarama` = `WaitForLocal` = `1` - see https://github.com/Shopify/sarama/blob/221ed1a25150fa98d750f2e2f33f58ff018238b4/config.go#L445 and https://github.com/Shopify/sarama/blob/221ed1a25150fa98d750f2e2f33f58ff018238b4/produce_request.go#L16

There are others like `auto.commit.interval.ms`.

**Comment by phamilton** [comment]
> > comparable to the Java client in most cases
> 
> it seems the Java client is much faster on the producer side. Any insights on why?

You are correct. Didn't look too much into the producer side as its trivial to scale the producers for performance needs. Trickier on the consumer side as you can only effectively scale to the number of partitions.

**Comment by phamilton** [comment]
> From a quick look, it seems like default configurations among libraries are different.
> 
> For example, `acks`
> 
> * `Java` = `1` - see https://kafka.apache.org/documentation/#producerconfigs
> * `librdkafka` = `-1` = `all brokers` - see https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md#topic-configuration-properties
> * `sarama` = `WaitForLocal` = `1` - see https://github.com/Shopify/sarama/blob/221ed1a25150fa98d750f2e2f33f58ff018238b4/config.go#L445 and https://github.com/Shopify/sarama/blob/221ed1a25150fa98d750f2e2f33f58ff018238b4/produce_request.go#L16
> 
> There are others like `auto.commit.interval.ms`.

Good catch on the producer acks. Didn't spend much time on the producer as its so trivially horizontally scalable.  

For the auto.commit.interval.ms that would only come into play on the consumer side not the producer side.  All 3 are committing offsets in the background outside of the message processing loop. It is possible that there is a slight performance hit from it though.

**Comment by davyodom** [comment]
Do we need to get deep into tuning all of these libraries here or can we agree on the direction of switching to Sarama here? The previous functional reasons that blocked Sarama usage before have since been resolved, and the performance and simplicity also point in that direction.

**Comment by phamilton** [comment]
Yes I should of probably made more clear that the performance tests ran were not meant to be a full comparison.  Mostly what we were interested in was any major differences between sarama and confluent-kafka-go.  Of which we certainly see on the consumption side a major difference. Though the code was checked in with certain settings, they were not the only ones ran with.  I did tweak the settings to try and get additional performance (especially with the confluent-kafka-go consumer, since there seems to be significant issues there).  The results show the best performance achieved.

**Comment by pierDipi** [comment]
I don't think we need to go deeper. 
Probably, a good next step is to improve re-usable pieces in `eventing-contrib` to create a library for both implementations. (see https://github.com/knative/eventing-contrib/tree/master/kafka/common/pkg/kafka).

**Comment by slinkydeveloper** [comment]
> Probably, a good next step is to improve re-usable pieces in eventing-contrib to create a library for both implementations.

+1 eventing-contrib already has some bits, we may extract even more and put them in kafka/common and share that code across the repos
